# Generated by Django 2.2.12 on 2020-06-09 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ablum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ablum_name', models.CharField(max_length=50)),
                ('release_year', models.DateField()),
                ('cover', models.ImageField(upload_to='cover')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=30)),
                ('total_song', models.IntegerField(default=0)),
                ('singer_img', models.ImageField(upload_to='singerImg')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_order', models.IntegerField(default=0)),
                ('song_name', models.CharField(max_length=50)),
                ('song_singer', models.CharField(max_length=50)),
                ('song_source', models.FileField(upload_to='source')),
                ('is_like', models.BooleanField(default=False)),
                ('song_type', models.CharField(choices=[('Pop', 'Pop'), ('J-Pop', 'J-Pop'), ('Jazz', 'Jazz'), ('Classic', 'Classic'), ('Blue', 'Blue'), ('EDM', 'EDM'), ('Other', 'Other')], default='Pop', max_length=7)),
                ('ablum_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ablum', to='main.Ablum')),
                ('release_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='main.Ablum')),
            ],
        ),
        migrations.AddField(
            model_name='ablum',
            name='ablum_singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer', to='main.Artist'),
        ),
        migrations.AddField(
            model_name='ablum',
            name='upLoad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
