# Generated by Django 2.2.12 on 2020-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200609_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language_type',
            field=models.CharField(choices=[('CH', '中文'), ('JP', '日文'), ('EN', '英文'), ('OTH', '其他')], default='CH', max_length=2),
        ),
    ]
